//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Makale
    {
        public int MakaleID { get; set; }
        public Nullable<int> YazarID { get; set; }
        public Nullable<int> KategoriID { get; set; }
        public string Baslık { get; set; }
        public string Icerik { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public string mp3 { get; set; }
    
        public virtual Kategori Kategori { get; set; }
        public virtual Yazar Yazar { get; set; }
    }
}
